#!/bin/bash

NAME=jms
DESC="Javascript Module Server"
BASEDIR=$(dirname $0)

checkdirs() {
    if [ ! -d "$BASEDIR/pid" ]; then
        mkdir "$BASEDIR/pid"
    fi

    if [ ! -d "$BASEDIR/logs" ]; then
        mkdir "$BASEDIR/logs"
    fi
}

start() {

    checkdirs

    cd $BASEDIR
    pm2 start processes.json > /dev/null 2>&1
    RET=$?
    exit $RET
}

stop() {

    cd $BASEDIR
    pm2 delete processes.json > /dev/null 2>&1
    RET=$?
    exit $RET

}

deploy () {

    cd $BASEDIR
	node bin/deploy.js $1 $2 $3 $4 $5

}

purge () {

    cd $BASEDIR
	node bin/purge-cache.js $1 $2 $3 $4 $5

}

restart () {

    checkdirs

    cd $BASEDIR
    pm2 restart processes.json > /dev/null 2>&1
    RET=$?
    exit $RET

}

status () {

    cd $BASEDIR
    node bin/status.js
    RET=$?
    exit $RET
}


case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status
	;;
	deploy)
		deploy $2 $3 $4 $5 $6
	;;
	restart|reload)
		restart
	;;
	purge)
		purge $2 $3 $4 $5 $6
	;;
*)
	echo $"Usage: $0 {start|stop|restart|deploy|status|purge}"
	exit 1
esac
exit 0
